// <auto-generated />
using System;
using IkematgahDegisim.DataAccess.Concerete.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IkematgahDegisim.DataAccess.Migrations
{
    [DbContext(typeof(IkematgahDegisimContext))]
    [Migration("20191210210405_ChangingToPropertyNames")]
    partial class ChangingToPropertyNames
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IkematgahDegisim.Core.Entities.Concerete.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ceptelefonNumarasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("durum")
                        .HasColumnType("bit");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("refreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("refreshTokenEndDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("sifreHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("sifreSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("soyad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("IkematgahDegisim.Core.Entities.Concerete.KullaniciOperasyonelTalep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("operationClaimId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KullaniciOperasyonelTalepler");
                });

            modelBuilder.Entity("IkematgahDegisim.Core.Entities.Concerete.OperasyonelTalep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OperasyonelTalepler");
                });

            modelBuilder.Entity("IkematgahDegisim.Entity.Concerete.Ikematgah", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ikematgahAdres")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("İkematgahlar");
                });

            modelBuilder.Entity("IkematgahDegisim.Entity.Concerete.Talep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("kalinanEvinAdresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("kiraci")
                        .HasColumnType("bit");

                    b.Property<bool>("onay")
                        .HasColumnType("bit");

                    b.Property<byte[]>("sozlesmeFotograf")
                        .HasColumnType("image");

                    b.Property<DateTime?>("talepTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("vatandasTalepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("vatandasTalepId");

                    b.ToTable("Talepler");
                });

            modelBuilder.Entity("IkematgahDegisim.Entity.Concerete.Teslimat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("teslimatToken")
                        .HasColumnType("int");

                    b.Property<int?>("vatandasTeslimatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("vatandasTeslimatId");

                    b.ToTable("Teslimatlar");
                });

            modelBuilder.Entity("IkematgahDegisim.Entity.Concerete.Vatandas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dogumTarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ikematgahId")
                        .HasColumnType("int");

                    b.Property<string>("soyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tcKimlik")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ikematgahId");

                    b.ToTable("Vatandaslar");
                });

            modelBuilder.Entity("IkematgahDegisim.Entity.Concerete.VatandasKisisel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ceptelefonNumarasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("evAdres")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KisiselBilgiler");
                });

            modelBuilder.Entity("IkematgahDegisim.Entity.Concerete.VatandasTalep", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("talepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VatandasTalepler");
                });

            modelBuilder.Entity("IkematgahDegisim.Entity.Concerete.VatandasTeslimat", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("teslimatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VatandasTeslimatlar");
                });

            modelBuilder.Entity("IkematgahDegisim.Entity.Concerete.Talep", b =>
                {
                    b.HasOne("IkematgahDegisim.Entity.Concerete.VatandasTalep", "vatandasTalep")
                        .WithMany("talepler")
                        .HasForeignKey("vatandasTalepId");
                });

            modelBuilder.Entity("IkematgahDegisim.Entity.Concerete.Teslimat", b =>
                {
                    b.HasOne("IkematgahDegisim.Entity.Concerete.VatandasTeslimat", "vatandasTeslimat")
                        .WithMany("teslimatlar")
                        .HasForeignKey("vatandasTeslimatId");
                });

            modelBuilder.Entity("IkematgahDegisim.Entity.Concerete.Vatandas", b =>
                {
                    b.HasOne("IkematgahDegisim.Entity.Concerete.Ikematgah", "ikematgah")
                        .WithMany("vatandaslar")
                        .HasForeignKey("ikematgahId");
                });

            modelBuilder.Entity("IkematgahDegisim.Entity.Concerete.VatandasKisisel", b =>
                {
                    b.HasOne("IkematgahDegisim.Entity.Concerete.Vatandas", "vatandas")
                        .WithOne("vatandasKisisel")
                        .HasForeignKey("IkematgahDegisim.Entity.Concerete.VatandasKisisel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IkematgahDegisim.Entity.Concerete.VatandasTalep", b =>
                {
                    b.HasOne("IkematgahDegisim.Entity.Concerete.Vatandas", "vatandas")
                        .WithOne("vatandasTalep")
                        .HasForeignKey("IkematgahDegisim.Entity.Concerete.VatandasTalep", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IkematgahDegisim.Entity.Concerete.VatandasTeslimat", b =>
                {
                    b.HasOne("IkematgahDegisim.Entity.Concerete.Vatandas", "vatandas")
                        .WithOne("vatandasTeslimat")
                        .HasForeignKey("IkematgahDegisim.Entity.Concerete.VatandasTeslimat", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
